name: client
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  dio: ^5.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.3
  meta: ^1.8.0
  jwt_decoder: ^2.0.1
  fpdart: ^0.6.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.3
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
